### ISSUE TITLE
dbt found two macros with the name "test_unique" in the namespace "dbt".

### ISSUE THREAD

**Issue by swanderz** [mikaelene/dbt-sqlserver#18]
80% chance I'm missing something obvious here... I _think_ it has to do w/ my conda env
 here goes anyway.

used `pip` to install dbt-sqlserver. `dbt debug` checks out no problem. However, I'm encountering the below issue with `dbt run`.
```
> dbt run -t sqlserver
Running with dbt=0.16.1
Encountered an error:
Compilation Error
  dbt found two macros with the name "test_unique" in the namespace "dbt". Since these macros have the same name and exist in the same namespace, dbt will be unable to decide which to call. To fix this, change the name of one of these macros:
  - macro.dbt_sqlserver.test_unique (macros/schema_tests.sql)
  - macro.dbt_sqlserver.test_unique (macros/schema_tests.sql)
```

here's the full stacktrace from the logs...
```python
Traceback (most recent call last):
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/task/runnable.py", line 351, in run
    self._runtime_initialize()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/task/runnable.py", line 107, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/task/runnable.py", line 75, in _runtime_initialize
    self.load_manifest()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/task/runnable.py", line 63, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/parser/manifest.py", line 646, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/parser/manifest.py", line 336, in load_all
    loader.load(internal_manifest=internal_manifest)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/parser/manifest.py", line 204, in load
    self.macro_hook(macro_manifest)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/perf_utils.py", line 21, in set_header
    adapter.connections.set_query_header(manifest)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/adapters/base/connections.py", line 46, in set_query_header
    self.query_header = MacroQueryStringSetter(self.profile, manifest)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/adapters/base/query_headers.py", line 75, in __init__
    ctx = self._get_context()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/adapters/base/query_headers.py", line 84, in _get_context
    return generate_query_header_context(self.config, self.manifest)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/context/configured.py", line 136, in generate_query_header_context
    return ctx.to_dict()
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/context/configured.py", line 121, in to_dict
    dct.update(self.get_macros())
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/context/configured.py", line 116, in get_macros
    nsp.add_macros(self.manifest.macros.values(), self._ctx)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/context/configured.py", line 76, in add_macros
    self.add_macro(macro, ctx)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/context/configured.py", line 66, in add_macro
    raise_duplicate_macro_name(macro_func.macro, macro, namespace)
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/exceptions.py", line 664, in raise_duplicate_macro_name
    node_2.unique_id, node_2.original_file_path
  File "/Users/anders.swanson/opt/anaconda3/lib/python3.7/site-packages/dbt/exceptions.py", line 363, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error
  dbt found two macros with the name "test_unique" in the namespace "dbt". Since these macros have the same name and exist in the same namespace, dbt will be unable to decide which to call. To fix this, change the name of one of these macros:
  - macro.dbt_sqlserver.test_unique (macros/schema_tests.sql)
  - macro.dbt_sqlserver.test_unique (macros/schema_tests.sql)
```

**Comment by swanderz** [comment]
ok. i'm slow, but now I've seen #16 and now I'm caught up.
