### ISSUE TITLE
error installing with pip

### ISSUE THREAD

**Issue by davehowell** [mikaelene/dbt-sqlserver#5]
I tried to run `pip install dbt-sqlserver` and it errored. Looks like you've vendored the pymssql lib in there and it has a dependency on Cython?  

I'm trying this on a Mac

```
Collecting dbt-sqlserver
  Downloading https://files.pythonhosted.org/packages/92/6a/805de0abd4ed1c823760282072f78fb66095e659e45376cfd82dec4b72f0/dbt_sqlserver-0.1.4.1-py3-none-any.whl
Collecting dbt-core>=0.14.0 (from dbt-sqlserver)
  Downloading https://files.pythonhosted.org/packages/62/ee/63b4b36a486487bf4713415736092a63f3654d023540d8cf31745debe75b/dbt-core-0.14.0.tar.gz (534kB)
     |████████████████████████████████| 542kB 9.2MB/s
Collecting pymssql>=2.1.4 (from dbt-sqlserver)
  Downloading https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz (691kB)
     |████████████████████████████████| 696kB 16.4MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/myself/Projects/py3test/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tx/gnjzcly97p94whybspstf9b00000gn/T/pip-install-v5n8y1mc/pymssql/setup.py'"'"'; __file__='"'"'/private/var/folders/tx/gnjzcly97p94whybspstf9b00000gn/T/pip-install-v5n8y1mc/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/tx/gnjzcly97p94whybspstf9b00000gn/T/pip-install-v5n8y1mc/pymssql/
    Complete output (7 lines):
    /Users/myself/Projects/py3test/.venv/lib/python3.7/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tx/gnjzcly97p94whybspstf9b00000gn/T/pip-install-v5n8y1mc/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mikaelene** [comment]
Hi @davehowell . Sorry for the really late replay. This somehow missed me completely. 

The more resent version uses pyodbc instead of pymsql. Have you tried 0.14.1?

Otherwise `pip install Cython ` should solve your problem

**Comment by davehowell** [comment]
Thanks I did install cython, I just thought perhaps the setup.py might need to include that but now you’re on pyodbc no need. I’m not currently working with mssql but thanks for sharing this with the community!
